---
title: "Over-representation analysis"
author: "Hani Kim"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary
This script runs over-representation analysis on granulocyte terms. 

# Loading 

## Packages
```{r, message = FALSE}
suppressPackageStartupMessages({
  library(clusterProfiler)
})
```

## Load HSPC Dx results
```{r}
load("/Users/hani/Dropbox (Sydney Uni)/Single Cell Reserach/SCProj-stable/Cepo_manuscript/Data/Dx_benchmark_result_HSPC.RData", verbose = T)
```

# Prepare results
```{r}
Dx.list <- list(
  Cepo=DS.res,
  Voom=Voom.res,
  DD=DD.res,
  MAST=MAST.res
)
```

# Perform over-representation analysis
```{r}
CapStr <- function(y) {
        c <- strsplit(y, " ")[[1]]
        paste(toupper(substring(c, 1,1)), substring(c, 2),
              sep="", collapse=" ")
}

capitalize <- function(charcter_string){
        sapply(charcter_string, CapStr)
}

gene <- names(DS.res[[1]]) # get global genes

n=100
Dx_top <- lapply(Dx.list, function(l) {
  t <- lapply(l, function(x) names(x)[1:n]) # use top 100 genes
  names(t) <- names(DS.res)
  return(t)
})
names(Dx_top) <- names(Dx.list)
        
enrich.list <- lapply(Dx_top, function(dx) { 

  t <- lapply(dx, function(topGenes) {
                genes <- topGenes
                gene.dat <- bitr(capitalize(tolower(gene)), fromType = "SYMBOL",
                                 toType = c("ENSEMBL", "SYMBOL","ENTREZID"),
                                 OrgDb = org.Mm.eg.db)
                gene <- gene.dat$ENTREZID[gene.dat$SYMBOL %in% capitalize(tolower(genes))]
                GO.dat <- enrichGO(gene = gene,`org.Mm.eg.db`, ont = "BP", pAdjustMethod = "BH", pvalueCutoff = 1)
                return(GO.dat)
  })
  names(t) <- names(Dx_top[[1]])
  return(t)
  
})
names(enrich.list) <- names(Dx_top)

save(enrich.list, file=paste0("../../../Data/trajectory_HSC_overrep_result_", n, ".RData"))
```

# Visualise results
```{r}
enrich.res <- lapply(enrich.list, function(x) {
  
  int_res <- lapply(x, function(res) {
    
    if (is.null(res) == F) {
      
      pvalue <- res@result[, "p.adjust"]
      names(pvalue) <- res@result[, "Description"]
      ratio1 <- as.numeric(sapply(strsplit(res@result[,"GeneRatio"], "/"), "[[", 1))
      ratio2 <- as.numeric(sapply(strsplit(res@result[,"GeneRatio"], "/"), "[[", 2))
      ratio <- ratio1/ratio2
      names(ratio) <- res@result[, "Description"]
      results <- list(pvalue, ratio)
      return(results)
      
    }
  })
  names(int_res) <- names(enrich.list[[1]])
  return(int_res)
  })
names(enrich.res) <- names(enrich.list)

pathways <- lapply(enrich.res, function(x) unique(unlist(lapply(sapply(x, "[[", 1), function(x) names(x)))))

counter <- 0
pvalue <- lapply(enrich.res, function(int_res) {
  counter <<- counter+1
  lapply(sapply(int_res, "[[", 1), function(x) {
    
    if (is.null(x) == F) {
      x[pathways[[counter]]]
    }
  })
})

counter <- 0
pvalue.rbind <- lapply(pvalue, function(x)  {
  counter <<- counter + 1
  t <- do.call(cbind, x)
  rownames(t) <- pathways[[counter]]
  colnames(t) <- names(enrich.list[[1]])
  t <- -log10(t)
  t[is.na(t)] <- 0
  
  t <- apply(t, 2, function(x) scales::rescale(x, to=c(0,10)))
  
  return(t)
})

pathwaystoPlot <- c("neutrophil chemotaxis",
                    "neutrophil migration",
                    "neutrophil extravasation",
                    "granulocyte differentiation",
                    "regulation of granulocyte differentiation",
                    "granulocyte chemotaxis",
                    "granulocyte migration",
                    "negative regulation of granulocyte differentiation",
                    "dense core granule localization",
                    "dense core granule transport",
                    "cerebellar granular layer morphogenesis",
                    "response to granulocyte macrophage colony-stimulating factor",
                    "secretory granule localization",
                    "cerebellar granular layer development",
                    "secretory granule organization")

my_cols <- c("#0D0887FF", "#6A00A8FF", "#B12A90FF","#E16462FF", "#FCA636FF", "#F0F921FF")

resgg <- lapply(1:length(pvalue.rbind), function(m) {
  mat <- pvalue.rbind[[m]]
dat.long <- reshape2::melt(mat[rownames(mat) %in% pathwaystoPlot,])
colnames(dat.long) <- c("pathway", "celltype", "neg.log10.pvalue")

dat.long$pathway <- factor(dat.long$pathway, levels = pathwaystoPlot)
dat.long$celltype <- factor(dat.long$celltype, levels = c("Gran","Myelocyte","HSCP","Meg", "Eryth", "MDP","Mono","Multi"))

ggpubr::ggballoonplot(
  dat.long[,1:3],
  fill="neg.log10.pvalue", shape=22) +
  coord_flip() + 
  scale_fill_gradientn(colors = my_cols) +
  theme_classic() + 
  theme(legend.position = "bottom",
        axis.line = element_blank(),            # disable axis lines
        axis.title = element_blank(),   
        axis.text.x = element_text(angle = 45, vjust = 0),# disable axis titles
        panel.border = element_blank(),        # disable panel border
        panel.grid.minor.x = element_blank()) 
})


unlist(lapply(pvalue, function(x) {
  lapply(pathwaystoPlot, function(y) {
    if (y %in% names(x$Gran)) {
      return(x$Gran[[y]])
    } else { return(NULL) }
  })
}))
```

```{r fig.height=20, fig.width=40}
do.call(ggpubr::ggarrange, c(resgg, ncol=4, nrow=1, common.legend=T)) %>% ggsave(filename="../../../Figures/trajectory_analysis/trajectory_HSC_overrep_granulocyte.pdf", height=6, width=28)
```

# Session info

```{r}
sessioninfo::session_info()
```

