---
title: "Paired boxplot of genes prioritised by Cepo"
author: "Hani Kim"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary
This script provide code to visualise the paired rankings of genes priorised by Cepo.

# Loading 

## Packages
```{r, message = FALSE}
suppressPackageStartupMessages({
  library(tidyverse)
  library(SingleCellExperiment)
  library(hdf5r)
  library(dyno)
  library(scater)
  library(ggplot2)
  library(tidyverse)
  library(dyntoy)
  library(dyneval)
  library(patchwork)
})

#dynwrap::test_docker_installation(detailed = TRUE)
```

## Load HSPC single cell data
```{r}
load("../../../Data/Dx_benchmark_result_HSPC.RData", verbose = T)
load("../../../Data/trajectory_sce_HSC.RData", verbose=T)
load("../../../Data/trajecotories_HSC_traj_dx_results.RData", verbose=T)
```

# Generate paired boxplot of genes prioritised by Cepo
```{r}
anchor.list =  list(Cepo=DS.res)
other.list =  list(Voom=Voom.res,
                  DD=DD.res,
                  MAST=MAST.res)
gene.list_scatter <- FindDivergentGenes(anchor.list, other.list)

gene.list.all <- list(Cepo=DS.res,
                  Voom=Voom.res,
                  DD=DD.res,
                  MAST=MAST.res)

ggtab <- lapply(1:length(gene.list_scatter), function(cty) {
  
  celltype <- names(gene.list_scatter)[[cty]]
  unique_DS <- gene.list_scatter[[cty]]
  
  ggrank <- lapply(c("Cepo", "Voom", "DD", "MAST"), function(dx) {
    
    x= 1:length(gene.list.all[[dx]][cty][[1]])
    names(x) <- names(gene.list.all[[dx]][cty][[1]])
    y=gene.list.all[[dx]][cty][[1]]
    
    gene <- sapply(names(x), function(i) ifelse(i %in% unique_DS, i, FALSE))
    idx_size <- ifelse(gene %in% unique_DS, 2, 1)
    idx_size[[length(idx_size)]] <- 1
    df <- data.frame(x=x, y=y, gene=gene, genenames=names(x), size=idx_size, method=dx, cty = names(gene.list_scatter)[[cty]])
    rownames(df) <- names(x)
    return(df)
  })
    ggrank <- do.call(rbind, ggrank)
    return(ggrank)
})
ggtab <- do.call(rbind, ggtab)
ggtab <- ggtab[!ggtab$gene == F,c(1,4,6,7)]
    
for (i in unique(ggtab$cty)) {
  
  dat <- ggtab[ggtab$cty %in% i,1:3]
  dat <- spread(dat,key=method, value=x)
  rownames(dat) <- dat[,1]
  dat <- dat[,-1]
  n = nrow(dat)
  dat <- melt(dat)
  for (r in 1:2) {
  dat <- rbind(dat[1:n,], dat)
  }
  dat$set <- rep(rep(1:3, each=n), 2)
  
  g <- lapply(1:3, function(x) {
    
    ggpaired(dat[dat$set==x,], x="variable", y="value",
             color = "variable", line.color = "gray", line.size = 0.4,
             palette = "jco")+
      stat_compare_means(paired = TRUE)
  })
  g <- do.call(ggpubr::ggarrange, c(g, ncol=3))
  g %>% ggsave(filename=paste0("../../../Figures/trajectory_analysis/trajectory_scatter_paired_", i,".pdf"), width=8, height=5)

}
```

# Session info

```{r}
sessioninfo::session_info()
```
