---
title: "Rare cell type analysis: visualisation"
author: "Hani Kim"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary
This script provide code to visualise the Dx results from the rare cell type analysis. 

# Loading 

## Packages
```{r, message = FALSE}
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(ggplot2)
  library(ggthemes)
  library(tidyverse)
})
```

## Load Dx results from full and subsampled data
```{r}
load("../../../Data/cellbench_Dx_benchmark_results.RData", verbose=T)
load("../../../Data/cellbench_DE_benchmark_results.RData", verbose=T)

load("../../../Data/cellbench_rare_celltype_five_percent.RData", verbose=T)
```


# Prepare Dx results
```{r}
Dx.res.list <- list(DS=DS.res, Voom=Voom.res, DD=DD.res, MAST=MAST.res)
Dx.results.list <- list(DS=results_DS, Voom=results_Voom, DD=results_DD, MAST=results_MAST)
```

# Generate scatter plot of example subsampled result against full set
```{r}
pdf(file="../../../Figures/rare_cell_type/cellbench_rare_cell_type_subsampled.pdf", width=15, height=10)
par(mfrow=c(3,4))
lapply(names(DS.res), function(x) {
  
  i=50 
  lapply(names(Dx.res.list), function(Dx) {
    
    Dx.res <- Dx.res.list[[Dx]]
    Dx.results <- Dx.results.list[[Dx]]
    idx <- names(Dx.res[[x]])
    c <- cor.test(Dx.res[[x]][idx], Dx.results[[x]][idx,i])$estimate
    plot(Dx.res[[x]][idx], Dx.results[[x]][idx, i], main=paste0(x, "_", c), xlab="all cells", ylab="5% of cells", col=alpha("black", 0.5), bty="n")
    abline(lm(Dx.results[[x]][idx,i]~Dx.res[[x]][idx]), col="red")
    abline(a=0,b=1, col="blue")
    
  })

})
dev.off()
```

# Generate boxplot of top genes for the rare cell type results (n=50)
```{r}
cell_type_rare <- lapply(names(DS.res), function(x) {
  
  cor.res <- lapply(names(Dx.res.list), function(Dx) {
    
    Dx.res <- Dx.res.list[[Dx]]
    Dx.results <- Dx.results.list[[Dx]]
    
    idx <- names(Dx.res[[x]])[1:40]
    
    coef <- unlist(lapply(1:ncol(Dx.results[[x]]), function(i) {
      
      cor.test(Dx.res[[x]][idx], Dx.results[[x]][idx,i])$estimate

    }))
    coef <- data.frame(celltype=x, method=Dx, cor=coef)
    return(coef)
  
  })
  cor.res <- do.call(rbind, cor.res)

  return(cor.res)
  
})

cell_type_rare <- do.call(rbind, cell_type_rare)
cell_type_rare$method <- factor(cell_type_rare$method, levels=c("DS", "Voom", "DD", "MAST"))

g <- ggplot(cell_type_rare, aes(x=method, y=cor, fill=method)) + 
  geom_boxplot(width=4) + facet_wrap(~celltype) + theme_classic() 
g %>% ggsave(filename="../../../Figures/rare_cell_type/cellbench_rare_cell_type_cor_boxplot.pdf", width=8, height=4)
```


# Session Info
```{r}
sessioninfo::session_info()
```
