---
title: "Differential analysis on haematopoeitic stem cell differentiation dataset"
author: "Hani Kim and Kevin Wang"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary
This script runs the benchmarking differential analysis algorithms on a HSPC differentiation single-cell dataset downloaded from [CytoTRACE](https://cytotrace.stanford.edu/).

# Loading 

## Packages
```{r, message = FALSE}
suppressPackageStartupMessages({
  library(tidyverse)
  library(SingleCellExperiment)
  library(hdf5r)
  library(dyno)
  library(scater)
  library(ggplot2)
  library(tidyverse)
  library(dyntoy)
  library(dyneval)
  library(patchwork)
})

#dynwrap::test_docker_installation(detailed = TRUE)
```

## Load HSPC single cell data
```{r}
traj <- readRDS("../../../Data/dataset_hspc_c1.rds")
```

## Source functions
```{r}
source("../../../R/Cepo.R") 
source("../../../R/doDE.R")
source("../../../R/doDD.R")
source("../../../R/utils.R")
```

# Process data
```{r}
#### generate metadata
meta <- data.frame(
  group=traj$Phenotype[!is.na(traj$Phenotype)]
)

#### expression matrix
exprs <- traj$exprMatrix
rownames(exprs) <- toupper(rownames(exprs))
exprs <- exprs[!is.na(rownames(exprs)),]
exprs <- exprs[!duplicated(rownames(exprs)),]
exprs <- exprs[,!is.na(traj$Phenotype)]

#### phenotypes 
table(traj$Phenotype)
```

# Visualisation trajectory
```{r fig.height=10, fig.width=10}
col <- RColorBrewer::brewer.pal(8, "Paired")

g1 <- ggplot(traj$output, aes(x=tSNE1, y=tSNE2, col=Phenotype)) + geom_point() + scale_color_manual(values=col) + 
  theme_classic() + theme(aspect.ratio = 1)

g2 <- ggplot(traj$output, aes(x=tSNE1, y=tSNE2, col=CytoTRACE)) + geom_point() +
  scale_color_viridis_c() + theme_classic() + theme(aspect.ratio = 1)

g3 <- ggplot(traj$output, aes(x=UMAP1, y=UMAP2, col=Phenotype)) + geom_point() + scale_color_manual(values=col) + theme_classic() + theme(aspect.ratio = 1)

g4 <- ggplot(traj$output, aes(x=UMAP1, y=UMAP2, col=CytoTRACE)) + geom_point() +
  scale_color_viridis_c() + theme_classic() + theme(aspect.ratio = 1)

ggpubr::ggarrange(g1,g2,g3,g4, ncol=2, nrow=2) %>%
  ggsave(filename="../../../Figures/trajectory_analysis/trajectory_RDM.pdf", width=10, height=10)
```

# Generate SCE object 
```{r}
#### filter lowly expressed genes
zprop <- rowSums(exprs == 0)/ncol(exprs)
mnz <- apply(exprs, 1, function(x) mean(x[x>0]))
idx <- mnz > 0.4 | zprop < 0.9
idx[is.na(idx)] <- FALSE
sum(table(idx)) == length(zprop) # filter 4911 and keep 10719 genes

exprs <- exprs[idx,]
dim(exprs)

#### generate SCE object
sce <- SingleCellExperiment(assay=list(counts=exprs),
                                      colData=meta)
sce <- scater::logNormCounts(sce)
save(sce, file="../../../Data/trajectory_sce_HSC.RData")
```

# Run Cepo and Dx algorithm
```{r}
##### generate cell type labels
cty <- factor(meta$group)

##### run Cepo
DS.res <- Cepo(logcounts(sce), cty)

##### run DD
system.time(DD <- doDD(logcounts(sce), cty))
DD.res <- getStats(DD, method="DD")

##### run Voom
Voom <- doVoom(logcounts(sce), cty)
Voom.res <- getStats(Voom, method="Voom")

##### run MAST
system.time(MAST <- doMAST(logcounts(sce), cty))
MAST.res <- getStats(MAST, method="MAST")

save(DS.res, 
     DD, DD.res,
     Voom, Voom.res,
     MAST, MAST.res,
     file="../../../Data/Dx_benchmark_result_HSPC.RData")
```

# Session info
```{r}
sessioninfo::session_info()
```
