---
title: "Dx analysis on cross-technology Cellbench data"
author: "Hani Kim"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary
This script runs the benchmarking differential analysis algorithms on the three Cellbench data (3 cell types) each generated from distinct single-cell technologies: 10X Chromium, CEL-seq, and Drop-seq. 

# Loading 

## Packages
```{r, message = FALSE}
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(MAST)
  library(limma)
  library(edgeR)
})
```

## Load 3-class cellbench data
```{r}
load("../../../Data/cellbench_sce_3class.RData", verbose=T)
```

## Source functions
```{r}
source("../../../R/Cepo.R") 
source("../../../R/doDE.R")
source("../../../R/doDD.R")
source("../../../R/utils.R")
```

# Prepare cross-platform datasets
```{r}
sce_platforms <- list(
  tenx = sce_10x_log,
  celseq = sce_CELseq2_log,
  dropseq = sce_Dropseq_log
)
```

# Find cell identity genes using each method
```{r}
cty <- factor(sce_10x_log$celltype)

### Cepo
Cepo_res <- lapply(sce_platforms, function(sce) {
  ds.res <- Cepo(logcounts(sce), sce$celltype)
  return(ds.res)
})
names(Cepo_res) <- names(sce_platforms)

### DD
DD_res <- lapply(sce_platforms, function(sce) {
  dd <- doDD(logcounts(sce), sce$celltype)
  dd.res <- getStats(dd, method="DD")
  return(dd.res)
})
names(DD_res) <- names(sce_platforms)

### Voom
Voom_res <- lapply(sce_platforms, function(sce) {
  voom <- doVoom(logcounts(sce), sce$celltype)
  voom.res <- getStats(voom, method="Voom")
  return(voom.res)
})
names(Voom_res) <- names(sce_platforms)

### MAST
MAST_res <- lapply(sce_platforms, function(sce) {
  mast <- doMAST(logcounts(sce), sce$celltype)
  mast.res <- getStats(mast, method="MAST")
  return(mast.res)
})
names(MAST_res) <- names(sce_platforms)

save(Cepo_res, DD_res, Voom_res, MAST_res, 
     file="../../../Data/cellbench_cross_technology_Dx_results.RData")
```

# Session Info
```{r}
sessioninfo::session_info()
```

