---
title: "Visualisation of Cepo results from cross-technology and batch Cellbench data"
author: "Hani Kim"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary
This script provide code to visualise the concordance in Cepo results between cross-technology and batch results. 

# Loading 

## Packages
```{r, message = FALSE}
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(ggplot2)
  library(ggthemes)
  library(UpSetR)
  library(scater)
  library(dplyr)
})
```

## Load 3-class cellbench data
```{r}
load("../../../Data/cellbench_sce_3class.RData", verbose=T)
```

## Source functions
```{r}
source("../../../R/Cepo.R") 
source("../../../R/doDE.R")
source("../../../R/doDD.R")
source("../../../R/utils.R")
```

# Load Dx results from cross-platforms
```{r}
load("../../../Data/cellbench_cross_technology_Dx_results.RData", verbose=T)

Dx.list <- list(DS=Cepo_res, DD=DD_res, Voom=Voom_res, MAST=MAST_res)
```

# Load Dx results from cross-batch
```{r}
##### check there are same number of genes as no filtering was performed
load("../../../Data/cellbench_Dx_benchmark_5cls_results.RData", verbose=T)
Dx.list$DS$batch2 <- DS.res
```

# Generate correlation plot 
```{r}
pdf(file="../../../Figures/rare_cell_type/cellbench_ggpairs_concordance.pdf", width=12, height=12)

idx <- names(Cepo_res[[1]][[1]])
celltype <- factor(names(Cepo_res[[1]]))
ggconcordance <- lapply(levels(celltype), function(x) {
  df.res <- lapply("DS", function(i) {
    df=data.frame(tenx=Dx.list[[i]][["tenx"]][[x]][idx],
                  celseq=Dx.list[[i]][["celseq"]][[x]][idx],
                  dropseq=Dx.list[[i]][["dropseq"]][[x]][idx],
                  batch=Dx.list[[i]][["batch2"]][[x]][idx]
    )
    rownames(df) = idx
    df <- na.omit(df)
    colnames(df) = paste0(x, "_", colnames(df))
    return(df)
  })
  return(df.res)
})
names(ggconcordance) <- levels(celltype)
ggconcordance <- do.call(cbind, lapply(ggconcordance, function(x) x[[1]]))

df=ggconcordance
res <- rcorr(as.matrix(df), type="spearman")
res_cor <- c(res$r)
res_cor <- matrix(res_cor, nrow=ncol(df), ncol=ncol(df))
rownames(res_cor) <- colnames(df)
colnames(res_cor) <- colnames(df)

my_col <- rev(RColorBrewer::brewer.pal(11, "Spectral"))
corrplot(res_cor, 
         method="color",
         p.mat = res$P, 
         sig.level = 0.01, 
         addCoef.col = "black",
         tl.col="black", tl.srt=45,
         col= colorRampPalette(my_col)(20)
)

dev.off()
```

# Session Info
```{r}
sessioninfo::session_info()
```
