---
title: "Generate hopach trees from the Pijuan Dx results"
author: "Hani Kim"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary
This script provide code to generate hopach trees from the Pijuan differential analysis results.

# Loading 

## Packages
```{r, message = FALSE}
suppressPackageStartupMessages({
  library(ggplot2)
  library(pheatmap)
  library(hopach)
})
```

## Load pijuan rank data and correlation matrix 
```{r}
load("../../../Data/pijuan_ranked_dx_result.RData", verbose=T)
load("../../../Data/pijuan_annotations.RData", verbose=T)
```

## Source functions
```{r}
source("../../../R/doHopach.R")
```

# Run hopach 
```{r}
res_hopach <- lapply(result_rank, function(x) runHOPACH(x, kmax=10, labels=TRUE))

lapply(1:4, function(x) {
  cty <- names(result_rank)[[x]]
  g <- res_hopach[[x]]$plot
  g %>% ggsave(filename=paste0("../../../Figures/pijuan/pijuan_hopach_distance_matrix_trees_", cty, ".pdf"), width=3, height=25)
})
```

# Session Info
```{r}
sessioninfo::session_info()
```

