---
title: "Cluster validation on Pijuan Dx results"
author: "Hani Kim"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary
This script performs cluster validation on the results of the Pijuan atlas data.

# Loading 

## Packages
```{r, message = FALSE}
suppressPackageStartupMessages({
  library(ggplot2)
  library(umap)
  library(clusterCrit)
})
```

## Load 3-class cellbench data
```{r}
load("../../../Data/pijuan_ranked_dx_result.RData", verbose=T)
load("../../../Data/pijuan_annotations.RData", verbose=T)
```

# Calculate and visualise silhoette index
```{r fig.height=8, fig.width=20}
pdf(file="../../../Figures/pijuan/pijuan_silhouette_plot.pdf", width=10, height=5)
par(mfrow=c(1,4))
lapply(result_cor, function(x) {
  sil <- cluster::silhouette(as.numeric(annot$celltype_major), 1-x)
  plot(sil, col=color_annot$celltype_major[c("Anterior Primitive Streak",
                                             "Blood prog/Ery", 
                                             "Ectoderm", "Endoderm1", "Endoderm2", 
                                             "ExE ectoderm", "Mesoderm", "Neural crest", "PGC")][sort(annot$celltype_major)])
  abline(v=summary(sil, mean)[4], col="red", lty="dotted")
})
dev.off()
```

# Session Info
```{r}
sessioninfo::session_info()
```

