---
title: "Visualisation of the Pijuan Dx results on low dimensional space"
author: "Hani Kim"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary
This script provides code to visualise the Pijuan rank data on TSNE, UMAP, and PCA. 

# Loading 

## Packages
```{r, message = FALSE}
suppressPackageStartupMessages({
  library(ggplot2)
  library(umap)
  library(Rtsne)
  library(stats)
  library(hopach)
})
```

## Load pijuan rank data and similarity matrix 
```{r}
load("../../../Data/pijuan_ranked_dx_result.RData", verbose=T)
load("../../../Data/pijuan_annotations.RData", verbose=T)
```

# Visualise results on low dimensional space
```{r}
result_dist_cor <- lapply(result_rank, function(x) {
  x <- hopach::distancematrix(t(x), d='cor')
  return(x)
})
names(result_dist_cor) <- names(result_rank[[1]])

counter <- 0
gg.res <- lapply(result_dist_cor, function(res) {
  counter <<- counter + 1
  dx_name <- names(result_dist_cor)[[counter]]
  
  res <- as.matrix(res)
  
  set.seed(2020)
  
  TSNE <- Rtsne::Rtsne(t(res))$Y
  UMAP <- umap::umap(t(res))$layout
  PCA <- stats::princomp(res)$loadings
  
  dftoplot <- data.frame(
    tdm1=TSNE[,1],
    tdm2=TSNE[,2],
    udm1=UMAP[,1],
    udm2=UMAP[,2],
    pdm1=PCA[,1],
    pdm2=PCA[,2]
  )
  return(dftoplot)
})

gg.pijuan <- lapply(1:ncol(annot), function(set) {
  
  lapply(gg.res, function(dftoplot) {
    
    gg <- ggplot(dftoplot, aes(x=pdm1, y=pdm2, col=annot[,set])) + 
      ggrastr::geom_point_rast(size=8, alpha=0.8) + 
      scale_color_manual(values=color_annot[[set]]) +
      theme_classic() + theme(aspect.ratio = 1, legend.position = "top")
    
    return(gg)
  })
  
})

pdf("../../../Figures/pijuan/pijuan_cell_type_matching_PCA_distancematrix.pdf", width=10, height=15)
ggpubr::ggarrange( do.call(ggpubr::ggarrange, c(gg.pijuan[[2]], ncol=4, nrow=1, common.legend=T)), 
                   do.call(ggpubr::ggarrange, c(gg.pijuan[[3]], ncol=4, nrow=1, common.legend=T)), 
                   do.call(ggpubr::ggarrange, c(gg.pijuan[[1]], ncol=4, nrow=1, common.legend=T)), ncol=1)
dev.off()
```

# Session Info
```{r}
sessioninfo::session_info()
```

