---
title: "Aggregation of Pijuan Dx results and generation of annotations"
author: "Hani Kim"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary
This script provides code to aggregate the differential analysis results from the Pijuan atlas data and provide details of how the annotation labels were generated.

# Loading 

## Packages
```{r, message = FALSE}
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(MAST)
  library(limma)
  library(edgeR)
  library(hopach)
})
```

# Aggregate Dx results from multiple stages
```{r}
stages <- c("E6.5", "E6.75", "E7.0", "E7.25", "E7.5", "E7.75", "E8.0", "E8.25", "E8.5")

path = "../../../Data/pijuan_classification_results/"

####### aggregate all results into list
Dx.result <- lapply(stage, function(stg) {
  load(paste0(path, "201125_pijuan_all_celltypes_dx_results_", stg,".RData"), verbose=T)
  return(list(Cepo=DS.res, Voom=Voom.res, DD=DD.res, MAST=MAST.res))
})
names(Dx.result) <- stages
save(Dx.result, file="../../../Data/pijuan_aggregated_dx_result.RData")
```

# Load aggregated pijuan data 
```{r}
load("../../../Data/pijuan_aggregated_dx_result.RData", verbose=T)

n=4 # number of Dx algorithms

####### group by Dx method
Dx.result_mat <- lapply(1:n, function(res) {
  res.list <- lapply(Dx.result, function(x) x[[res]])
  names(res.list) <- names(Dx.result)
  
  n_stage = length(res.list)
  res.mat <- lapply(1:n_stage, function(stg) {
    idx <- names(res.list[[stg]][[1]])
    mat <- do.call(cbind, lapply(res.list[[stg]], function(celltype) celltype[idx]))
    return(mat)
  })
  names(res.mat) <- names(Dx.result)
  
  idx <- rownames(res.mat[[1]])
  res.mat.stage <- do.call(cbind, lapply(res.mat, function(celltype) celltype[idx,]))
  colnames(res.mat.stage) <- paste0(rep(names(res.mat), sapply(res.mat, ncol)), 
                                    "_", colnames(res.mat.stage))
  
  return(res.mat.stage)
})

### remove heterogeneous cell type label "mixed gastrulation" if present
Dx.result_mat <- lapply(Dx.result_mat, function(mat) {
  idx <- sapply(strsplit(as.character(colnames(mat)), "_"), "[[", 1) %in% "mixed"
  m <- mat[,!idx]
  return(m)
})

### rank genes by Dx score
result_rank <- lapply(Dx.result_mat, function(x) {
  apply(x, 2, rank)
})
names(result_rank) <- names(Dx.result[[1]])

### generate correlation matrix
result_cor <- lapply(result_rank, function(x) {
  x <- cor(x, method="spearman")
  return(x)
})
names(result_cor) <- names(Dx.result[[1]])

save(result_rank, result_cor, file="../../../Data/pijuan_ranked_dx_result.RData")
```

# Generate annotations
```{r}
stage <- sapply(strsplit(colnames(Dx.result_mat[[1]]), "_"), "[[", 1)
celltype <- sapply(strsplit(colnames(Dx.result_mat[[1]]), "_"), "[[", 2)

celltype_major <- celltype

celltype_major[celltype_major %in% c("Surface ectoderm", 
                                     "Rostral neurectoderm", 
                                     "Caudal neurectoderm", 
                                     "Forebrain/Midbrain/Hindbrain", 
                                     "Spinal cord", 
                                     "Caudal Mesoderm", 
                                     "Caudal epiblast", 
                                     "Epiblast", 
                                     "NMP", 
                                     "Primitive Streak")] <- "Ectoderm"
celltype_major[celltype_major %in% c("Visceral endoderm", 
                                     "Parietal endoderm",
                                     "ExE endoderm")] <- "Endoderm1"
celltype_major[celltype_major %in% c("Def. endoderm",
                                     "Notochord", 
                                     "Gut")] <- "Endoderm2"
celltype_major[celltype_major %in% c("Blood progenitors 1", 
                                     "Blood progenitors 2", 
                                     "Haematoendothelial progenitors", 
                                     "Erythroid1",
                                     "Erythroid2",
                                     "Erythroid3",
                                     "Endothelium")] <- "Blood prog/Ery"
celltype_major[celltype_major %in% c("Mixed mesoderm", 
                                     "Pharyngeal mesoderm", 
                                     "Nascent mesoderm", 
                                     "Intermediate mesoderm",
                                     "Paraxial mesoderm", 
                                     "Somitic mesoderm", 
                                     "Mesenchyme", 
                                     "ExE mesoderm", 
                                     "Allantois", 
                                     "Cardiomyocytes")] <- "Mesoderm"

stage_colors = RColorBrewer::brewer.pal(9, "YlGnBu")
names(stage_colors) <- unique(stage)

celltype_colors = colorRampPalette(RColorBrewer::brewer.pal(12, "Paired"))(length(unique(celltype)))
names(celltype_colors) <- unique(celltype)

celltype_major_colors = colorRampPalette(RColorBrewer::brewer.pal(12, "Paired"))(length(unique(celltype_major)))
names(celltype_major_colors) <- unique(celltype_major)

color_annot <- list(
  stage=stage_colors,
  celltype=celltype_colors,
  celltype_major=celltype_major_colors
)

annot <- data.frame(
  stage=as.factor(stage),
  celltype=as.factor(celltype),
  celltype_major=as.factor(celltype_major))
rownames(annot) <- colnames(Dx.result_mat[[1]])

save(color_annot, annot, file="../../../Data/pijuan_annotations.RData")
```

# Session Info
```{r}
sessioninfo::session_info()
```

