---
title: "Densities of simulated differential stability genes"
author: "Hani Kim and Kevin Wang"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary
This script generates density plots of the simulated differential stability genes. 

# Loading 

## Packages
```{r, message = FALSE}
suppressPackageStartupMessages({
  library(ggplot2)
  library(plyexperiment)
  library(ggthemes)
})
```

## Source functions
```{r}
source("../../../R/simulateDS.R")
```

## Load simulated scRNA-seq datasets
```{r}
load("../../../Data/201210_simulation_stability_genes.RData", verbose=T)
load("../../../Data/201210_simulation_params.RData", verbose=T)

sim_logcounts = sim %>% logcounts %>% rm_cols_rows_zeroes()
```

# Generate histogram of differentially stimulated genes (all combinations)
```{r}
set.seed(123)
param_grid_viz = expand.grid(
  add_zero=seq(2,14,by=2),
  sd_scale=seq(1,3.4,by=0.4)) %>%
  as_tibble() 
param_grid_viz

#####ggplot
set.seed(123)
x = sim_logcounts[ds_index[100], ]
gg.sim.eg <- lapply(1:nrow(param_grid_viz), function(i) {
  y = replace_ds_genes_v2(x, labels, 
                          mean_scale = 1,
                          sd_scale = param_grid_viz[i,][[2]],
                          add_zero = param_grid_viz[i,][[1]])

  dftoplot <- data.frame(exprs=c(x[labels == "Group1"], y[labels == "Group2"]),
                         celltype=c(rep("Group1", length(x[labels == "Group1"])),
                                    rep("Group2", length(y[labels == "Group2"]))),
                         sd_scale=param_grid_viz[i,][[2]], add_zero=param_grid_viz[i,][[1]])
                                    return(dftoplot)
})
gg.sim.eg <- do.call(rbind, gg.sim.eg)

pdf(file="../../../Figures/simulation/simulation_distributions_full.pdf", width=20, height=20)
  ggplot(gg.sim.eg, aes(x=exprs, fill=celltype)) + 
  geom_density(alpha=.2) + 
  scale_fill_manual(values=c("#FF6666", "#66EBFF")) + 
  facet_wrap(~sd_scale + add_zero, ncol=7) +
  theme_clean()
dev.off()
```

# Session Info
```{r}
sessioninfo::session_info()
```
