---
title: "Generation of heatmaps from correlation matrix on Pijuan Dx results"
author: "Hani Kim"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary
This script provide code to generate the heatmaps of the correlation matrix between the 196 differential analysis statistics from the Pijuan atlas data.

# Loading 

## Packages
```{r, message = FALSE}
suppressPackageStartupMessages({
    library(ggplot2)
    library(pheatmap)
})
```

## Load pijuan rank data and correlation matrix 
```{r}
load("../../../Data/pijuan_ranked_dx_result.RData", verbose=T)
load("../../../Data/pijuan_annotations.RData", verbose=T)
```

# Generate pheatmaps
```{r}
counter <- 0
lapply(result_cor, function(res.mat) {
  counter <<- counter + 1
  cty <- names(result_cor)[[counter]]
  g <- pheatmap(res.mat, show_rownames = T, show_colnames = F, legend = F,
                annotation_col = annot[,2:3], annotation_colors=color_annot[2:3]
                #treeheight_col = 0, treeheight_row = 0, annotation_legend = F,legend = F,
                ) 
  g %>% ggsave(filename=paste0("../../../Figures/pijuan/pijuan_heatmap_", cty, ".pdf"), width=15, height=15)
})
```

# Session Info
```{r}
sessioninfo::session_info()
```

