---
title: "AUC heatmap of simulation results"
author: "Hani Kim and Kevin Wang"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary
This script generates AUC heatmap to demonstrate the accuracy of differential analysis methods to detect differential stability genes in the simulation datasets.

# Loading 

## Packages
```{r, message = FALSE}
suppressPackageStartupMessages({
  library(tidyverse)
  library(SingleCellExperiment)
  library(yardstick)
  library(ggpubr)
  library(ROSE)
  library(RColorBrewer)
})
```

## Source functions
```{r}
source("../../../R/simulateDS.R")
```

## Load simulated scRNA-seq datasets
```{r}
load("../../../Data/201210_simulation_stability_genes.RData", verbose=T)
load("../../../Data/201210_simulation_params.RData", verbose=T)

load("../../../Data/simulation_dx_results_201210.RData", verbose=T)
load("../../../Data/simulation_de_results_201210.RData", verbose=T)
```

# Prepare Dx results
```{r}
sim_dx_result <- list(
  Cepo=sim_ds_res,
  Voom=sim_Voom_res,
  DD=sim_DD_res,
  MAST=sim_MAST_res
)
```

# Calculate AUC
```{r}
prob.Dx <- lapply(1:length(sim_dx_result), function(res) {
  dx <- names(sim_dx_result)[[res]]
  unlist(lapply(1:length(sim_dx_result[[res]]), function(x) {
    true_label = factor(ifelse(rownames(sim_ds) %in% ds_index, "DS", "Other"))
    pred_prob = rank(sim_dx_result[[res]][[x]]$Group1[rownames(sim_ds)], ties.method = "random", na.last = T)
    pred <- yardstick::roc_auc_vec(truth=true_label, estimate=pred_prob)
    return(pred)
  }))
})
names(prob.Dx) <- names(sim_dx_result)
```

# Generate heatmap
```{r}
sim_dx_result_mat <- rbind(matrix(nrow=7, ncol=7, prob.Dx[["Cepo"]]), 
                           matrix(nrow=7, ncol=7, prob.Dx[["Voom"]]), 
                           matrix(nrow=7, ncol=7, prob.Dx[["DD"]]),
                           matrix(nrow=7, ncol=7, prob.Dx[["MAST"]])
)

colnames(sim_dx_result_mat) <- 1:ncol(sim_dx_result_mat)
rownames(sim_dx_result_mat) <- 1:nrow(sim_dx_result_mat)

annot_row <- data.frame(
  method=rep(c("Cepo","Voom","DD","MAST"), each=7),
  sd.scale=rep(seq(1,3.4,by=0.4), 4)
)
rownames(annot_row) <- 1:nrow(sim_dx_result_mat)

annot_col <- data.frame(
  zprop=rep(c(2,4,6,8,10,12,14))
)
rownames(annot_col) <- 1:ncol(sim_dx_result_mat)

my_pal = colorRampPalette(viridis::magma(n=30)[5:30])
pheatmap(sim_dx_result_mat, cluster_rows = F, 
         cluster_cols = F, color=my_pal(35),
         border_color = "grey",
         annotation_row = annot_row, annotation_col = annot_col, show_rownames = F, show_colnames = F) %>% 
  ggsave(filename ="../../../Figures/simulation/simulation_AUROC_heatmap.pdf", width=9, height=20)
```

# Session Info
```{r}
sessioninfo::session_info()
```
