---
title: "AUCROC curves of simulation results"
author: "Hani Kim and Kevin Wang"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary
This script generates AUCROC curves to demonstrate the accuracy of differential analysis methods to detect differential stability genes in the simulation datasets.

# Loading 

## Packages
```{r, message = FALSE}
suppressPackageStartupMessages({
  library(tidyverse)
  library(SingleCellExperiment)
  library(yardstick)
  library(ggpubr)
  library(ROSE)
})
```

## Source functions
```{r}
source("../../../R/simulateDS.R")
```

## Load simulated scRNA-seq datasets
```{r}
load("../../../Data/201210_simulation_stability_genes.RData", verbose=T)
load("../../../Data/201210_simulation_params.RData", verbose=T)

load("../../../Data/simulation_dx_results_201210.RData", verbose=T)
load("../../../Data/simulation_de_results_201210.RData", verbose=T)
```

# Prepare Dx results
```{r}
sim_dx_result <- list(
  Cepo=sim_ds_res,
  Voom=sim_Voom_res,
  DD=sim_DD_res,
  MAST=sim_MAST_res
)

### check number of genes are equal
# max(sapply(sim_dx_result[[1]], function(x) length(x[[1]])))
# max(sapply(sim_dx_result[[2]], function(x) length(x[[1]])))
# max(sapply(sim_dx_result[[3]], function(x) length(x[[1]])))
# max(sapply(sim_dx_result[[4]], function(x) length(x[[1]])))
```

# Generate AUCROC curves (ggplot version)
```{r}
pdf(file="../../../Figures/simulation/simulation_AUCROC_curves.pdf", width=15, height=15)

gg.auc <- lapply(1:length(sim_dx_result[[1]]), function(x) {
  
  tbl_all <- lapply(1:length(sim_dx_result), function(res) {
    dx <- names(sim_dx_result)[[res]]
    truth = ifelse(rownames(sim_ds) %in% ds_index, "DS", "Other") %>% factor()
    pred = sim_dx_result[[res]][[x]]$Group1[rownames(sim_ds)] %>% rank(na.last = T)
    method = rep(dx, length(truth))
    tbl = tibble(truth, pred, method) 
    return(tbl)
    })
  
  tbl_all <- do.call(rbind, tbl_all)
  
  tbl_all %>% group_by(method) %>%
  yardstick::roc_curve(truth = truth, pred) %>% 
    ggplot(aes(x = 1 - specificity, y = sensitivity,
               colour = method)) +
    geom_path(size = 0.5, show.legend = F) +
    geom_abline(lty = 2, col="red") +
    scale_color_manual(values=RColorBrewer::brewer.pal(6, "Set3")[c(1,6,3,4)]) +
    coord_equal() + theme_classic() + 
    theme(
          axis.text.x=element_blank(),
          axis.text.y=element_blank(),
          axis.ticks.x=element_blank(),
          axis.ticks.y=element_blank(),
          legend.position = "none",
          panel.border = element_blank(),
          panel.background = element_blank()
          )
  
})
ggpubr::ggarrange(do.call(ggpubr::ggarrange, c(gg.auc[1:7], ncol=1, nrow=7)),
          do.call(ggpubr::ggarrange, c(gg.auc[8:14], ncol=1, nrow=7)),
          do.call(ggpubr::ggarrange, c(gg.auc[15:21], ncol=1, nrow=7)),
          do.call(ggpubr::ggarrange, c(gg.auc[22:28], ncol=1, nrow=7)),
          do.call(ggpubr::ggarrange, c(gg.auc[29:35], ncol=1, nrow=7)),
          do.call(ggpubr::ggarrange, c(gg.auc[36:42], ncol=1, nrow=7)),
          do.call(ggpubr::ggarrange, c(gg.auc[43:49], ncol=1, nrow=7)),
          ncol=7)
dev.off()
```

# Session Info
```{r}
sessioninfo::session_info()
```

