---
title: "Visualisation of multiple trajectory analysis of HSPC differentiation"
author: "Hani Kim and Kevin Wang"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary
This script visualises the results of the multiple trajectory analysis on the HSPC differentiation dataset using [dynverse](https://dynverse.org/). 

# Loading 

## Packages
```{r, message = FALSE}
suppressPackageStartupMessages({
    library(tidyverse)
    library(dyno)
    library(patchwork)
    library(dynplot)
    library(furrr)
    library(ggplot2)
})

#dynwrap::test_docker_installation(detailed = TRUE)
```

## Load HSPC single cell data and Dx results
```{r}
load(file = "../../../Data/trajecotories_HSC_traj_dx_results_all_methods.RData", verbose = TRUE)
load("../../../Data/trajectory_sce_HSC.RData", verbose=T)
```

## Source functions
```{r}
source("../../../R/utils.R")
```

# Single example (not run)
```{r, eval = FALSE}
plot_dimred(result_grid$model[[1]], grouping = result_grid$dyno_data[[1]]$cell_info$group)

plot_dimred(result_grid$model[[1]], 
            grouping = result_grid$dyno_data[[1]]$cell_info$group,
            dimred = dyndimred::dimred_mds,
            expression_source = result_grid$dyno_data[[1]]$expression)

plot_dimred(result_grid$model[[2]], grouping = result_grid$dyno_data[[2]]$cell_info$group)

plot_dimred(result_grid$model[[2]], 
            grouping = result_grid$dyno_data[[2]]$cell_info$group,
            dimred = dyndimred::dimred_mds,
            expression_source = result_grid$dyno_data[[2]]$expression)

plot_dimred(result_grid$model[[3]], 
            grouping = result_grid$dyno_data[[3]]$cell_info$group,
            dimred = dyndimred::dimred_mds,
            expression_source = result_grid$dyno_data[[3]]$expression)
```

# Generate dimensional reduction plots
```{r}
for(this_features_name in unique(result_grid$features_name)){
    sub_result_by_features_name = result_grid %>% 
        dplyr::filter(features_name == this_features_name)
    
    list_figures = purrr::map(
        .x = 1:nrow(sub_result_by_features_name),
        .f = function(i){
            plot_dimred(
                sub_result_by_features_name$model[[i]],
                grouping = sub_result_by_features_name$dyno_data[[i]]$cell_info$group,
                dimred = dyndimred::dimred_mds,
                expression_source = sub_result_by_features_name$dyno_data[[i]]$expression) +
                labs(title = paste0("Features: ", sub_result_by_features_name$features_name[[i]], "\n",
                                    "Method: ", sub_result_by_features_name$method_id[[i]]))})
    
    all_figures = patchwork::wrap_plots(list_figures, nrow = 2) +
        plot_layout(guides = "collect") &
        theme(legend.position = "bottom")
    
    message("Saving plot for ", this_features_name)
    
    ggsave(filename = paste0("../../../Figures/trajectory_analysis/trajectory_HSC_by_features/", this_features_name, ".pdf"), 
           plot = all_figures, width = 12, height = 6)
}
```

# Count bifurcations 
```{r}
set.seed(2020)
root <- sample(colnames(sce[sce$group %in% "Stem"]), 1)

result_model <- result_grid$model

bifur_count_new <- lapply(seq_along(result_model), function(x) {
    
    tmp <- result_model[[x]]
    tmp_dyno <- result_grid$dyno_data[[x]]
    
    tmp <- add_root(tmp, root_cell_id = root)
    tmp <- add_pseudotime(tmp)
    
    tree_type <- tmp$trajectory_type
    
        tree_type_final <- c()
        if(tree_type %in% c("tree", "bifurcation")) {
            
            if (sum(names(sort(table(tmp_dyno$group_info$group[tmp$pseudotime > quantile(tmp$pseudotime, 0.7)]), decreasing=T)) %in% c("Myelocyte", "MDP")) == 2) {tree_type_final <- "bifurcation_correct"} else {tree_type_final <- "bifurcation_incorrect"}
            
        } else {tree_type_final <- "linear"}
        return(tree_type_final)
})
bifur_count <- unlist(bifur_count_new)

traj_type = result_grid %>% 
    dplyr::transmute(
        features_name,
        method_name, traj_type = purrr::map_chr(.x = model, "trajectory_type"))
traj_type$traj_type_new <- bifur_count

traj_type_sum = traj_type %>% 
    group_by(features_name) %>% 
    summarise(num_bifur = sum(traj_type_new %in% "bifurcation_correct")) %>% 
    tidyr::separate(
        col = features_name, 
        into = c("dx_method", "num_features"), sep = "__") %>% 
    dplyr::mutate(num_features = as.integer(num_features) %>% 
                      factor)
traj_type_sum$dx_method <- factor(traj_type_sum$dx_method, levels=c("Cepo", "Voom", "DD", "MAST"))
```

# Visualise as heatmap
```{r}
gg <- traj_type_sum %>% 
    ggplot(aes(x = num_features, 
               y = dx_method, 
               fill = num_bifur,
               label = num_bifur)) +
    geom_tile() +
    geom_text() +
    scale_fill_distiller(palette = "Blues", direction = 1) +
    theme_classic() +
    theme(legend.position = "bottom") 
gg %>% ggsave(filename = paste0("../../../Figures/trajectory_analysis/trajectories_multiple_methods.pdf"), width=10, height = 5)
```

# Visualise as piechart
```{r}
traj_type_pie = traj_type %>% 
    group_by(features_name) %>% 
    summarise(num_bifur = sum(traj_type_new %in% "bifurcation_correct"),
              num_other = sum(traj_type_new %in% "bifurcation_incorrect"),
              num_linear = sum(traj_type_new %in% "linear")
              ) %>% 
    tidyr::separate(
        col = features_name, 
        into = c("dx_method", "num_features"), sep = "__") %>% 
    dplyr::mutate(num_features = as.integer(num_features) %>% 
                      factor)
traj_type_pie$dx_method <- factor(traj_type_pie$dx_method, levels=c("Cepo", "Voom", "DD", "MAST"))
traj_type_pie <- traj_type_pie[traj_type_pie$num_features %in% c(200), c(1,3:5)]
traj_type_pie <- reshape2::melt(traj_type_pie)

gg <- traj_type_pie %>% 
  ggplot(aes(x = "", 
             y = value, 
             fill = variable)) +
  geom_bar(width = 1, stat = "identity") + 
  facet_grid(~dx_method) + 
  coord_polar("y") + 
  theme_classic() +
  theme(legend.position = "bottom") 
gg %>% ggsave(filename = paste0("../../../Figures/trajectory_analysis/trajectories_multiple_methods_pie.pdf"), width=10, height = 5)
```

# Session info
```{r}
sessioninfo::session_info()
```
