---
title: "Plot UMAP of Pijuan data"
author: "Hani Kim"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary
This script generates UMAP visualisations of the [Pijuan embryogenesis dataset](https://www.nature.com/articles/s41586-019-0933-9) and bar plot of cell numbers grouped by cell type and time point.

# Loading 

## Packages
```{r, message = FALSE}
suppressPackageStartupMessages({
  library(ggplot2)
  library(ggpubr)
})
```

## Load low dimension coordinates and annotation labels
```{r}
pijuan_dftoplot <- read.delim("../../../Data/pijuan_reduced_dimension.txt", sep="\t")
load("../../../Data/pijuan_annotations.RData", verbose=T)
```

# Plot UMAP colored by original and major lineage/cell-type labels
```{r}
g1 <- ggplot(pijuan_dftoplot, aes(x=UMAP1, y=UMAP2,  col=celltype)) +
  ggrastr::geom_point_rast(alpha=0.1, size=0.3) + 
  scale_color_manual(values = color_annot$celltype) + 
  theme_classic() + theme(aspect.ratio = 1, legend.position = "bottom")
g2 <- ggplot(pijuan_dftoplot, aes(x=UMAP1, y=UMAP2, col=celltype_major)) +
  ggrastr::geom_point_rast(alpha=0.1, size=0.3) + 
  scale_color_manual(values = color_annot$celltype_major) + 
  theme_classic() + theme(aspect.ratio = 1, legend.position = "none")
g3 <- ggplot(pijuan_dftoplot, aes(x=UMAP1, y=UMAP2, col=stage)) +
  ggrastr::geom_point_rast(alpha=0.1, size=0.3) + scale_color_brewer(palette="YlGnBu") + 
  theme_classic() + theme(aspect.ratio = 1, legend.position = "bottom")

g1 %>% ggsave(filename="../../../Figures/pijuan/pijuan_full_umap_celltype.pdf", width=10, height=5)
g2 %>% ggsave(filename="../../../Figures/pijuan/pijuan_full_umap_celltype_major.pdf", width=10, height=5)
g3 %>% ggsave(filename="../../../Figures/pijuan/pijuan_full_umap_stage.pdf", width=10, height=5)
```

# Plot barplot resolved by lineage and time-point
```{r}
groups <- list(Mesoderm="Mesoderm",
               Blood= "Blood prog/Ery",
               Endoderm1="Endoderm1",
               Endoderm2="Endoderm2",
               other = c("ExE ectoderm", "PGC", "Anterior Primitive Streak", "ExE ectoderm", "Neural crest")
               )

lapply(groups, function(x) {
    par(mfrow=c(1,1), mar=c(15,4,3,3))
    tmp <- pijuan_dftoplot[pijuan_dftoplot$celltype_major %in% x,]
    names_idx <- names(sort(table(tmp$celltype), decreasing=T))
    barplot(table(tmp$stage,tmp$celltype)[,names_idx], col=RColorBrewer::brewer.pal(9, "YlGnBu"), las=2)
})


tmp <- paste(na.omit(pijuan_dftoplot$celltype_major), na.omit(pijuan_dftoplot$celltype), sep="_")
tmp <- levels(factor(tmp))
m <- sapply(strsplit(tmp, "_"), "[[", 1)
names(m) <- sapply(strsplit(tmp, "_"), "[[", 2)

names_idx <- names(sort(table(pijuan_dftoplot$celltype), decreasing=T))
names_idx <- paste0(paste0(rep(letters, each=2), 1:2)[1:37], "_", names_idx)
names_idx <- paste0(m[names(sort(table(pijuan_dftoplot$celltype), decreasing=T))], "_", names_idx)
names(names_idx) <- names(sort(table(pijuan_dftoplot$celltype), decreasing=T))
names_idx <- sort(names_idx)

pdf(file="../../../Figures/pijuan/pijuan_full_barplot.pdf", width=10, height=5)
barplot(table(pijuan_dftoplot$stage,pijuan_dftoplot$celltype)[,names(names_idx)], col=RColorBrewer::brewer.pal(9, "YlGnBu"), las=2)
dev.off()
```

# Session Info
```{r}
sessioninfo::session_info()
```


