---
title: "fetal tissue atlas"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#devtools::install_github(repo = "mojaveazure/loomR", ref = "develop")
suppressPackageStartupMessages({
    library(HDF5Array)
    library(DelayedArray)
    library(DelayedMatrixStats)
    library(BiocParallel)
    library(LoomExperiment)
    library(lobstr)
    library(loomR)
})
```

## load metadata
```{r}
# list.files("~/project_diffAtlas/data/RNA/metadata")
data_path = "/albona/nobackup/biostat/datasets/singlecell/human_fetal/"
list.files(data_path)

# meta_cells <- readRDS("~/project_diffAtlas/data/RNA/metadata/df_cell.RDS")
# meta_genes <- readRDS("~/project_diffAtlas/data/RNA/metadata/df_gene.RDS")

# meta_cells = vroom::vroom(paste0(data_path, "GSE156793_S1_metadata_cells.txt.gz"), delim = ",")
# meta_genes = vroom::vroom(paste0(data_path, "GSE156793_S2_Metadata_genes.txt.gz"), delim = ",")
# 
# table(meta_cells$Main_cluster_name)
# table(meta_genes$gene_type)
```

## connect to loom object

```{r, eval = FALSE}
scle = import(paste0(data_path, "GSE156793_S3_gene_count.loom"), type = "SingleCellLoomExperiment")
lobstr::obj_size(scle)/1e9
lobstr::mem_used()/1e9
class(scle)

rowdata = rowData(scle)
coldata = colData(scle)
table(coldata$Main_cluster_name)
table(coldata$Organ_cell_lineage)
# table(coldata$Main_cluster_name, coldata$Organ_cell_lineage)

scle_subset = scle[rowdata$gene_type == "protein_coding", ]
assay(scle_subset, "counts") = assay(scle_subset, "matrix")
assay(scle_subset, "matrix") = NULL

BPPARAM = BiocParallel::MulticoreParam(workers = 10)
DelayedArray:::set_verbose_block_processing(TRUE)
DelayedArray::setAutoBlockSize(size = .Machine$integer.max - 1)
scle_subset2 = scater::logNormCounts(scle_subset)
rownames(scle_subset2) = rowData(scle_subset2)$gene_id
colnames(scle_subset2) = colData(scle_subset2)$sample

library(HDF5Array)

HDF5Array::saveHDF5SummarizedExperiment(x = scle_subset2, 
                                        dir = paste0(data_path, "protein_coding_subset_normalised.h5"), 
                                        verbose = TRUE, replace = TRUE)
```

## run Cepo
```{r}
library(Cepo)
```

```{r}
DelayedArray:::set_verbose_block_processing(TRUE)
DelayedArray::setAutoBlockSize(size = .Machine$integer.max - 1)
DelayedArray::getAutoBlockSize()
BPPARAM = BiocParallel::MulticoreParam(workers = 10)
DelayedArray::setAutoBPPARAM(BPPARAM = BPPARAM)
DelayedArray::getAutoBPPARAM()

scle_subset2 = HDF5Array::loadHDF5SummarizedExperiment(dir = paste0(data_path, "protein_coding_subset_normalised.h5"))
exprsMat_da = DelayedArray::DelayedArray(assay(scle_subset2, "logcounts"))
coldata = colData(scle_subset2)

class(seed(exprsMat_da))

t1 = Sys.time()
main_output = Cepo::Cepo(exprsMat = exprsMat_da, 
                   cellTypes = coldata$Main_cluster_name)
t2 = Sys.time()
t2 - t1

t3 = Sys.time()
organ_output = Cepo::Cepo(exprsMat = exprsMat_da, 
                                 cellTypes = coldata$Organ_cell_lineage)
t4 = Sys.time()
t4 - t3
save(main_output, organ_output, file = "fetal_cepo_output.RData")
#identical(mat_output, da_output)
#
#library(microbenchmark)
#microbenchmark::microbenchmark(
#mat_output = Cepo(exprsMat = exprsMat, cellTypes = cellTypes),
#da_output = Cepo(exprsMat = exprsMat_da, cellTypes = cellTypes), times = 10)
```

