---
title: "Cellbench density plots"
author: "Hani Kim"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary
This script generates density plot of differentially stable genes identified from Cepo and genes de-prioritised by Cepo compared to non-DS methods.

# Loading 

## Packages
```{r, message = FALSE}
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(ggplot2)
  library(ggthemes)
})
```

## Load 3-class cellbench data and dx results
```{r}
load("../../../Data/cellbench_sce_3class.RData", verbose=T)
rm(sce_CELseq2_log)
rm(sce_Dropseq_log)

load("../../../Data/cellbench_DE_benchmark_results.RData", verbose=T)
load("../../../Data/cellbench_Dx_benchmark_results.RData", verbose=T)
```

## Source functions
```{r}
source("../../../R/utils.R")
```

### Identify DS genes
```{r}
celltype <- factor(sce_10x_log$celltype)

gene.list <- list(Cepo=DS.res,
                  Voom=Voom.res,
                  MAST=MAST.res,
                  DD=DD.res)

H1975 <- c("MT1L","ENG")
H2228 <- c("BIRC3", "CYP1B1")
HCC827 <- c("KRTCAP3","MAL2")

DS.genes <- list(H1975=H1975,
                  H2228=H2228,
                  HCC82=HCC827)
names(DS.genes) <- NULL

## Compare ranking of genes between methods
#lapply(1:3, function(x) {
#  
#  t <- do.call(cbind, lapply(1:4, function(i) {
#    genes <- gene.list[[i]][[x]]
#    sapply(unlist(DS.genes), function(g) which(names(genes) %in% g))
#  }))
#  colnames(t) <- c("DS", "DD", "Voom", "MAST")
#  t
#  })
```

# Histogram of top DS genes
```{r}
Dx.gene <- DS.genes
cty <- factor(sce_10x_log$celltype)

gg.density <- lapply(1:nlevels(cty), function(celltype) {
  
  n=length(Dx.gene[[celltype]])
  Dx <- Dx.gene[[celltype]][1:n]
  df <- as.data.frame(t(logcounts(sce_10x_log)[Dx,]))
  df$celltype <- as.character(cty)
  
  my_col <- c("#FF6666", "green", "blue")
  names(my_col) <- levels(cty)
  my_col <- my_col[[celltype]]
  lapply(1:n, function(i) {
    dftoplot <- df[,c(i,ncol(df))]
    genename <- colnames(dftoplot)[[1]]
    colnames(dftoplot) <- c("gene", "celltype")
    ggplot(dftoplot, aes(x=gene)) + 
      geom_histogram(aes(y=..density..), colour="black", fill="white", bins=15) +
      facet_wrap(~celltype, scales="free_y", dir="v") + 
      ggtitle(genename) + 
      geom_density(alpha=.2, fill=my_col) + 
      theme_classic() + theme(axis.title.x=element_blank(), axis.title.y=element_blank(), 
                              strip.background = element_blank(), strip.text.x = element_blank())
  })
  
})

n = unique(sapply(gg.density, length))
g <- ggpubr::ggarrange(do.call(ggpubr::ggarrange, c(gg.density[[1]], ncol=n)),
                  do.call(ggpubr::ggarrange, c(gg.density[[2]], ncol=n)),
                  do.call(ggpubr::ggarrange, c(gg.density[[3]], ncol=n)), ncol=3) 
g %>% ggsave(file="../../../Figures/cellbench/cellbench_density_DS.pdf", width=15, height=5)
```

# Histogram of top DE genes
```{r fig.height=25, fig.width=25}
H1975 <- c("PPP1CA","MRPL11")
H2228 <- c("RAC1P2","HINT1")
HCC827 <- c("YBX1","UQCRH")

DE.genes <- list(H1975=H1975,
                  H2228=H2228,
                  HCC82=HCC827)
names(DE.genes) <- NULL

## Compare ranking of genes between methods
#lapply(1:3, function(x) {
#  
#  t <- do.call(cbind, lapply(1:4, function(i) {
#    genes <- gene.list[[i]][[x]]
#    sapply(unlist(DE.genes), function(g) which(names(genes) %in% g))
#  }))
#  colnames(t) <- c("DS", "DD", "Voom", "MAST")
#  t
#  })

Dx.gene <- DE.genes
cty <- factor(sce_10x_log$celltype)

gg.density <- lapply(1:nlevels(cty), function(celltype) {
  
  n=length(Dx.gene[[celltype]])
  Dx <- Dx.gene[[celltype]][1:n]
  df <- as.data.frame(t(logcounts(sce_10x_log)[Dx,]))
  df$celltype <- as.character(cty)
  
  my_col <- c("#FF6666", "green", "blue")
  names(my_col) <- levels(cty)
  my_col <- my_col[[celltype]]
  lapply(1:n, function(i) {
    dftoplot <- df[,c(i,ncol(df))]
    genename <- colnames(dftoplot)[[1]]
    colnames(dftoplot) <- c("gene", "celltype")
    ggplot(dftoplot, aes(x=gene)) + 
      geom_histogram(aes(y=..density..), colour="black", fill="white", bins=15) +
      facet_wrap(~celltype, scales="free_y", dir="v") + 
      ggtitle(genename) + 
      geom_density(alpha=.2, fill=my_col) + 
      theme_classic() + theme(axis.title.x=element_blank(), axis.title.y=element_blank(), 
                              strip.background = element_blank(), strip.text.x = element_blank())
  })
  
})

n = unique(sapply(gg.density, length))
g <- ggpubr::ggarrange(do.call(ggpubr::ggarrange, c(gg.density[[1]], ncol=n)),
                  do.call(ggpubr::ggarrange, c(gg.density[[2]], ncol=n)),
                  do.call(ggpubr::ggarrange, c(gg.density[[3]], ncol=n)), ncol=3) 
g %>% ggsave(file="../../../Figures/cellbench/cellbench_density_DE.pdf", width=15, height=5)
```

# Session Info
```{r}
sessioninfo::session_info()
```

