---
title: "Cellbench Dx analysis (5 cell-types)"
author: "Hani Kim"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary
This script contains code to run Cepo on the Cellbench data (5 cell types). 

# Loading 

## Packages
```{r, message = FALSE}
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(MAST)
  library(limma)
  library(edgeR)
})
```

## Load 3-class cellbench data
```{r}
load("../../../Data/cellbench_sce_5class.RData", verbose=T)
rm(sce_CELseq2_log)
rm(sce_Dropseq_log)
```

## Source functions
```{r}
source("../../../R/Cepo.R") 
source("../../../R/doDE.R")
source("../../../R/doDD.R")
source("../../../R/utils.R")
```

# Find cell identity genes 
```{r}
##### generate cell type labels
cty <- factor(sce_10x_5cl_log$celltype)

##### run Cepo
DS.res <- Cepo(logcounts(sce_10x_5cl_log), cty)

save(DS.res,
     file="../../../Data/cellbench_Dx_benchmark_5cls_results.RData")
```

# Session Info
```{r}
sessioninfo::session_info()
```

