---
title: "Cellbench Dx analysis (3 cell-types)"
author: "Hani Kim"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary
This script runs the benchmarking differential analysis algorithms on the Cellbench data (3 cell types). 

# Loading 

## Packages
```{r, message = FALSE}
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(MAST)
  library(limma)
  library(edgeR)
})
```

## Load 3-class cellbench data
```{r}
load("../../../Data/cellbench_sce_3class.RData", verbose=T)
rm(sce_CELseq2_log)
rm(sce_Dropseq_log)
```

## Source functions
```{r}
source("../../../R/Cepo.R") 
source("../../../R/doDE.R")
source("../../../R/doDD.R")
source("../../../R/utils.R")
```

# Find cell identity genes 
```{r}
##### generate cell type labels
cty <- factor(sce_10x_log$celltype)

##### run Cepo
DS.res <- Cepo(logcounts(sce_10x_log), cty)

##### run DD
system.time(DD <- doDD(logcounts(sce_10x_log), cty))
DD.res <- getStats(DD, method="DD")

save(DS.res,
     DD, DD.res,
     file="../../../Data/cellbench_Dx_benchmark_results.RData")

##### run Limma
Limma <- doLimma(logcounts(sce_10x_log), cty)
Limma.res <- getStats(Limma, method="Limma")

##### run Voom
Voom <- doVoom(logcounts(sce_10x_log), cty)
Voom.res <- getStats(Voom, method="Voom")

##### run EdgeR
EdgeR <- doEdgeR(counts(sce_10x_log), cty) 
EdgeR.res <- getStats(EdgeR, method="EdgeR")

##### run T-test
ttest <- doTest(logcounts(sce_10x_log), cty)
ttest.res <- getStats(ttest, method="ttest")

##### run Wilcoxon test
Wilcoxon <- doWilcoxon(logcounts(sce_10x_log), cty)
Wilcoxon.res <- getStats(Wilcoxon, method="Wilcoxon")

##### run MAST
system.time(MAST <- doMAST(logcounts(sce_10x_log), cty))
MAST.res <- getStats(MAST, method="MAST")

save(Limma, Limma.res, 
     Voom, Voom.res,
     MAST, MAST.res,
     ttest, ttest.res,
     Wilcoxon, Wilcoxon.res,
     EdgeR, EdgeR.res, 
     file="../../../Data/cellbench_DE_benchmark_results.RData")
```

# Session Info
```{r}
sessioninfo::session_info()
```
